export type EmployeeType = {
    id: number;
    employee_code: string;
    name: string;
    position: string;
    daily_rate: string | number;
    base_salary: string | number;
    hourly_rate: string | number;
    address?: string;
    contact_number?: string;
    tin?: string;
    sss_no?: string;
    pagibig_no?: string;
    philhealth_no?: string;
    sss_contribution?: string | number;
    pagibig_contribution?: string | number;
    philhealth_contribution?: string | number;
    emergency_loan?: string | number;
    withholding_tax?: string | number;
    cash_advance_balance?: string | number;
    pending_advancement_payout?: string | number;
    created_at: string;
    updated_at: string;
};
